### ISSUE TITLE
C: add a default ID for async events

### ISSUE THREAD

**Issue by slabasan** [flux-framework/PerfFlowAspect#107]

**Comment by tpatki** [comment]
I checked the codebase on the C side: it seems like the async functionality for ID is correct in the C code. The `before_async` and `after_async` functions call the `encode_event`, which takes in an ID as an input parameter and that gets set to the before/after counter value. There are however, no tests for this on the C side yet, so we need to add some more tests. Opened a separate issue for the tests, and closing this issue.
