### ISSUE TITLE
Simple usage statistics included as part of trace

### ISSUE THREAD

**Issue by tpatki** [flux-framework/PerfFlowAspect#23]
Adding CPU usage, memory usage, GPU usage may be useful as part of trace in addition to timing information. While time series data may be an option, simple aggregated statistics at annotation boundary/pointcuts (max, min, and average with timestamp info for max/min) may be useful. 

Some useful links: 

- https://pypi.org/project/psutil/ 
- https://pypi.org/project/GPUtil/
- https://pypi.org/project/memory-profiler/

**Comment by slabasan** [comment]
Closed with CPU/memory usage in #75
