### ISSUE TITLE
A global/module level enable flag

### ISSUE THREAD

**Issue by FrankD412** [flux-framework/PerfFlowAspect#3]
I find the ability to profile code useful, especially with the Chrome tracer -- however, it's cumbersome to inject the trace decorators each time I want to perform tracing. I know that `matplotlib` has some module-level settings for things, but some way to place the infrastructure once and then be able to turn off tracing for production would be really helpful.

**Comment by dongahn** [comment]
Yes. One of the advantages of AOP is to do this through a modular way. Once I have a minimal viable, I will add more controls in the form of both environment variables and TOML config.
