### ISSUE TITLE
Cannot compile PerfFlow Aspect on LC x86 systems

### ISSUE THREAD

**Issue by ilumsden** [flux-framework/PerfFlowAspect#49]
While trying to integrate PerfFlow Aspect into [DYAD's](https://github.com/flux-framework/dyad) new Autotools-based build system, I ran into issues trying to compile PerfFlow Aspect on LC's x86 systems, namely Catalyst.

In particular, the issue appears to occur when compiling WeavePass. More specifically, I get the following compilation errors:

```
/usr/tce/packages/clang/clang-10.0.1/include/llvm/ADT/PointerUnion.h:93:26: error: constexpr variable 'NumLowBitsAvailable' must be initialized by a constant expression
    static constexpr int NumLowBitsAvailable = lowBitsAvailable<PTs...>();
                         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/usr/tce/packages/clang/clang-10.0.1/include/llvm/ADT/PointerIntPair.h:145:17: error: static_assert expression is not an integral constant expression
  static_assert(PtrTraits::NumLowBitsAvailable <
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/usr/tce/packages/clang/clang-10.0.1/include/llvm/ADT/PointerIntPair.h:76:17: error: incomplete definition of type 'llvm::PointerIntPairInfo<void *, 1, llvm::pointer_union_detail::PointerUnionUIntTraits<llvm::MetadataAsValue *, llvm::Metadata *> >'
    Value = Info::updateInt(Info::updatePointer(0, PtrVal),
            ~~~~^~
```

For reference, I was using the following modules/libraries for dependencies on Catalyst:
* `clang/10.0.1`
* `cmake/3.23.1`
* Other dependencies are satisfied by system defaults

After doing a bit of digging myself, I found a [discussion from LLVM](https://lists.llvm.org/pipermail/llvm-dev/2019-September/134922.html) recommending the explicit use of `libc++` by adding `-stdlib=libc++`. When I did that, the compilation of WeavePass appeared to work, but I got the following error when building the smoketests:
```
error: unable to load plugin '../weaver/weave/libWeavePass.so': '../weaver/weave/libWeavePass.so: undefined symbol: _ZNK4llvm12FunctionPass17createPrinterPassERNS_11raw_ostreamERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE'
```

**Comment by tpatki** [comment]
@slabasan Was this addressed by the build restructuring we did?
