### ISSUE TITLE
Move CPU_MEM_USAGE to an internal config variable

### ISSUE THREAD

**Issue by slabasan** [flux-framework/PerfFlowAspect#79]
`CPU_MEM_USAGE` is currently an environment variable, but in PerfFlowAspect, the config options are specified using `PERFFLOW_OPTIONS`

**Comment by slabasan** [comment]
@alizalisan Do we still need to do this on the python side as well?

**Comment by alizalisan** [comment]
Yes, missed that one. Will get it done later today.
